<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="Application Test Suite" tests="1" assertions="0" failures="0" errors="1" time="0.000000">
    <testsuite name="Tests\Feature\sProOrderCreate\sProOrderCreateTimeTest" file="/var/www/tests/Feature/sProOrderCreate/sProOrderCreateTimeTest.php" tests="1" assertions="0" failures="0" errors="1" time="0.000000">
      <testcase name="testSProTimeAPIWithValidPhoneNumber" class="Tests\Feature\sProOrderCreate\sProOrderCreateTimeTest" file="/var/www/tests/Feature/sProOrderCreate/sProOrderCreateTimeTest.php" line="50" assertions="0" time="0.000000">
        <error type="PHPUnit_Framework_Exception">Tests\Feature\sProOrderCreate\sProOrderCreateTimeTest::testSProTimeAPIWithValidPhoneNumber
PHPUnit_Framework_Exception: array:2 [
  "code" =&gt; 400
  "message" =&gt; null
]

</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
